# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dkirby/CS585

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dkirby/CS585

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dkirby/CS585/CMakeFiles /home/dkirby/CS585/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dkirby/CS585/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CS585_test

# Build rule for target.
CS585_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CS585_test
.PHONY : CS585_test

# fast build rule for target.
CS585_test/fast:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/build
.PHONY : CS585_test/fast

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) -f external/gtest/CMakeFiles/googletest.dir/build.make external/gtest/CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

tests/test_class.o: tests/test_class.cpp.o
.PHONY : tests/test_class.o

# target to build an object file
tests/test_class.cpp.o:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/tests/test_class.cpp.o
.PHONY : tests/test_class.cpp.o

tests/test_class.i: tests/test_class.cpp.i
.PHONY : tests/test_class.i

# target to preprocess a source file
tests/test_class.cpp.i:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/tests/test_class.cpp.i
.PHONY : tests/test_class.cpp.i

tests/test_class.s: tests/test_class.cpp.s
.PHONY : tests/test_class.s

# target to generate assembly for a file
tests/test_class.cpp.s:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/tests/test_class.cpp.s
.PHONY : tests/test_class.cpp.s

tests/trivial.t.o: tests/trivial.t.cpp.o
.PHONY : tests/trivial.t.o

# target to build an object file
tests/trivial.t.cpp.o:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/tests/trivial.t.cpp.o
.PHONY : tests/trivial.t.cpp.o

tests/trivial.t.i: tests/trivial.t.cpp.i
.PHONY : tests/trivial.t.i

# target to preprocess a source file
tests/trivial.t.cpp.i:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/tests/trivial.t.cpp.i
.PHONY : tests/trivial.t.cpp.i

tests/trivial.t.s: tests/trivial.t.cpp.s
.PHONY : tests/trivial.t.s

# target to generate assembly for a file
tests/trivial.t.cpp.s:
	$(MAKE) -f CMakeFiles/CS585_test.dir/build.make CMakeFiles/CS585_test.dir/tests/trivial.t.cpp.s
.PHONY : tests/trivial.t.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CS585_test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... googletest"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
	@echo "... tests/test_class.o"
	@echo "... tests/test_class.i"
	@echo "... tests/test_class.s"
	@echo "... tests/trivial.t.o"
	@echo "... tests/trivial.t.i"
	@echo "... tests/trivial.t.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

